
export const USER_SPREADSHEET_FILENAME = 'สมุดวัดตัวลูกค้า (Tailor App Data)'; // Default filename in user's Drive

export const FIELD_LABELS_TH = {
  APP_TITLE: 'สมุดวัดตัวช่างตัดเสื้อ',
  INSTRUCTIONS_TITLE: 'คำแนะนำการวัดตัว',
  INSTRUCTION_1: 'วัดให้พอดี ไม่ต้องเผื่อ',
  INSTRUCTION_2: 'ถ้าต้องการแบบใส่หลวม หรือแบบฟิตพอดีให้แจ้งได้',
  INSTRUCTION_3: 'กรุณาเลือกหน่วยวัด (นิ้ว หรือ ซม.) ค่าเริ่มต้นคือ นิ้ว',
  
  CUSTOMER_INFO_TITLE: 'ข้อมูลลูกค้า',
  MEASUREMENTS_COL1_TITLE: 'ขนาดตัว (ส่วนบนและทั่วไป)',
  MEASUREMENTS_COL2_TITLE: 'ขนาดตัว (ส่วนล่างและเพิ่มเติม)',
  NOTES_FABRIC_TITLE: 'หมายเหตุและผ้า',
  
  NAME: 'ชื่อ-นามสกุล ลูกค้า',
  NICKNAME: 'ชื่อเล่น',
  ADDRESS: 'ที่อยู่',
  PHONE: 'เบอร์โทรศัพท์',
  DATE: 'วันที่วัด',

  UNIT_SELECTION_LABEL: 'เลือกหน่วยวัด:',
  UNIT_CM: 'เซนติเมตร (ซม.)',
  UNIT_INCH: 'นิ้ว (inches)',
  UNIT_CM_SHORT: 'ซม.',
  UNIT_INCH_SHORT: 'นิ้ว',
  UNIT_USED_LABEL: 'หน่วยวัด:',

  FRONT_LENGTH: 'ยาวหน้า',
  BACK_LENGTH: 'ยาวหลัง',
  SIDE_LENGTH: 'ยาวข้าง',
  SHOULDER: 'ไหล่',
  FRONT_SHOULDER_WIDTH: 'บ่าหน้า',
  BACK_SHOULDER_WIDTH: 'บ่าหลัง',
  NECK_CIRCUMFERENCE: 'รอบคอ',
  ARMHOLE: 'รักแร้',
  CHEST_CIRCUMFERENCE: 'รอบอก',
  BUST_DISTANCE: 'อกห่าง',
  BUST_HEIGHT: 'อกสูง',
  WAIST_CIRCUMFERENCE: 'รอบเอว',
  UPPER_HIP_CIRCUMFERENCE: 'สะโพกเล็ก (บน)',
  HIP_CIRCUMFERENCE: 'สะโพกใหญ่ (ล่าง)',
  SKIRT_LENGTH: 'ความยาวกระโปรง/กางเกง',
  SLEEVE_LENGTH: 'แขนยาว',
  SLEEVE_WIDTH_AT_ELBOW: 'รอบแขน (ข้อศอก)',
  SHIRT_LENGTH_TO_WRIST: 'ความยาวเสื้อ (ถึงข้อมือ)',
  OVERALL_LENGTH: 'ตัวยาว (ความยาวชุด)',

  SITTING_WAIST: 'รอบเอวขณะนั่ง',
  WAIST_TO_KNEE: 'เอวถึงเข่า',
  KNEE_CIRCUMFERENCE: 'รอบเข่า',
  THIGH_CIRCUMFERENCE: 'รอบต้นขา',
  CALF_CIRCUMFERENCE: 'รอบน่อง/ปลายขา',
  WAIST_TO_ANKLE_LENGTH: 'เอวถึงข้อเท้า',
  ANKLE_CIRCUMFERENCE: 'รอบข้อเท้า',
  CROTCH_DEPTH: 'เป้า (กางเกง)',

  NOTES: 'หมายเหตุเพิ่มเติม',
  FABRIC_SAMPLE_DESCRIPTION: 'ลักษณะผ้า/แบบที่ต้องการ',

  SAVE_BUTTON: 'บันทึกข้อมูล',
  UPDATE_BUTTON: 'อัปเดตข้อมูล',
  CANCEL_BUTTON: 'ยกเลิก',
  ADD_NEW_MEASUREMENT: 'เพิ่มข้อมูลลูกค้าใหม่',
  CUSTOMER_RECORDS: 'รายการลูกค้า',
  NO_RECORDS: 'ยังไม่มีข้อมูลลูกค้าที่บันทึกไว้',
  DELETE_BUTTON: 'ลบรายการนี้',
  CONFIRM_DELETE_MESSAGE: 'คุณแน่ใจหรือไม่ว่าต้องการลบข้อมูลของลูกค้าท่านนี้?',
  EDIT_BUTTON: 'แก้ไขข้อมูล',
  VIEW_DETAILS_BUTTON: 'ดู/แก้ไข',
  NAME_MISSING: 'ไม่ได้ระบุชื่อ',
  TOGGLE_CUSTOMER_INFO_BUTTON: 'แสดง/ซ่อนข้อมูลลูกค้า',
  SEARCH_PLACEHOLDER: 'ค้นหาด้วยชื่อ, ชื่อเล่น หรือเบอร์โทร...',
  NO_MATCHING_RECORDS_FOUND: 'ไม่พบข้อมูลลูกค้าที่ตรงกับการค้นหา',

  SIGN_IN_WITH_GOOGLE: 'ลงชื่อเข้าใช้ด้วย Google',
  SIGN_OUT_GOOGLE: 'ออกจากระบบ Google',
  SYNCING_DATA: 'กำลังซิงค์ข้อมูลกับ Google Drive',
  SYNCED_WITH_GOOGLE_SHEETS: 'ข้อมูลบันทึกใน Google Sheet ของคุณแล้ว',
  ERROR_SYNCING_DATA: 'เกิดข้อผิดพลาดในการซิงค์ข้อมูลกับ Google Drive',
  USING_LOCAL_STORAGE: 'ใช้ที่จัดเก็บข้อมูลในเครื่อง (ลงชื่อเข้าใช้ Google เพื่อบันทึกไปยัง Google Drive ของคุณ)',
  GOOGLE_SHEETS_PROMPT: 'ข้อมูลจะถูกบันทึกไปยัง Google Sheet ใน Google Drive ของคุณ',
  CONFIG_MISSING_TITLE: 'การตั้งค่า Google Sheets ไม่สมบูรณ์', // Kept for other potential config issues but primary one removed from App.tsx
  CONFIG_MISSING_MESSAGE: 'กรุณาตรวจสอบการตั้งค่า Client ID ในโค้ดของแอปพลิเคชัน (App.tsx) เพื่อใช้งาน Google Services', // Adjusted message
  LOADING_DATA: 'กำลังโหลดข้อมูล',
  LOADING_APP_DATA: 'กำลังเตรียมแอปพลิเคชัน',
  FOOTER_SLOGAN: 'ออกแบบมาเพื่อความสะดวกในการบันทึกข้อมูล',

  AUTHENTICATED_SEARCHING_SHEET: 'ลงชื่อเข้าใช้สำเร็จ กำลังค้นหา/สร้างไฟล์ข้อมูลใน Google Drive ของคุณ...',
  SPREADSHEET_FOUND_LOADING_DATA: 'พบไฟล์ข้อมูลแล้ว กำลังโหลดข้อมูลลูกค้า...',
  SPREADSHEET_NOT_FOUND_CREATING: 'ไม่พบไฟล์ข้อมูลเดิม กำลังสร้างไฟล์ใหม่ใน Google Drive ของคุณ...',
  SPREADSHEET_CREATED_SETUP_HEADERS: 'สร้างไฟล์ข้อมูลสำเร็จ กำลังตั้งค่าหัวตาราง...',
  ERROR_DRIVE_OPERATION: 'เกิดข้อผิดพลาดในการเข้าถึง Google Drive',
  ERROR_GAPI_NOT_READY: 'Google API Client ยังไม่พร้อมใช้งาน',
  ERROR_GIS_NOT_READY: 'Google Identity Service ยังไม่พร้อมใช้งาน',
  ERROR_AUTHENTICATING: 'เกิดข้อผิดพลาดในการยืนยันตัวตนกับ Google',
  ERROR_INITIALIZING_GAPI: 'เกิดข้อผิดพลาดในการเริ่มต้น Google API Client',
  ERROR_SHEET_HEADER_MISMATCH_ATTEMPT_FIX: 'หัวตารางใน Sheet ไม่ตรงกับที่คาดไว้ กำลังพยายามแก้ไข...',
  ERROR_EMPTY_RESPONSE: 'ไม่พบข้อมูลหรือการตอบกลับว่างเปล่า',
  GOOGLE_SHEETS_STORAGE: 'Google Sheets',
  ERROR_LOADING_LOCAL_DATA: 'เกิดข้อผิดพลาดในการโหลดข้อมูลจากที่จัดเก็บในเครื่อง',
  ERROR_SAVING_LOCAL_DATA: 'เกิดข้อผิดพลาดในการบันทึกข้อมูลลงที่จัดเก็บในเครื่อง',
  SETTING_UP_SHEET_HEADERS: 'กำลังตั้งค่าหัวตารางใน Google Sheet...',
  HEADERS_CONFIGURED_SUCCESS: 'ตั้งค่าหัวตารางสำเร็จแล้ว',
  ERROR_SETTING_UP_HEADERS: 'เกิดข้อผิดพลาดในการตั้งค่าหัวตาราง',
  ERROR_PERMISSION_DENIED_SHEETS: 'ไม่มีสิทธิ์เข้าถึง Google Sheets อาจต้องให้สิทธิ์อีกครั้ง',
  SAVING_TO_LOCAL_STORAGE_SIGN_IN_PROMPT: 'กำลังบันทึกลงในเครื่อง กรุณาลงชื่อเข้าใช้เพื่อบันทึกไปยัง Google Drive',
  DELETING_FROM_LOCAL_STORAGE_SIGN_IN_PROMPT: 'กำลังลบจากข้อมูลในเครื่อง กรุณาลงชื่อเข้าใช้เพื่อดำเนินการกับข้อมูลใน Google Drive',
};
